spring.application.name=real-estate-ai
spring.datasource.url=jdbc:postgresql://localhost:5432/real_estate_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8081
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

aws.region=ap-south-1
aws.s3.bucket-name=realestate-ai-property-images-sahil